#!/usr/bin/env python3
"""Audit the K2 residual after removing the provisional backreaction component."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "evidence"
DOCS = ROOT / "docs"

SPLIT_ROW = EVIDENCE / "backreaction_k2_component_split_row.csv"
SPLIT_ZONE = EVIDENCE / "backreaction_k2_component_split_zone.csv"

OUT_ROW = EVIDENCE / "k2_residual_after_backreaction_row.csv"
OUT_ZONE = EVIDENCE / "k2_residual_after_backreaction_zone.csv"
OUT_SUMMARY = EVIDENCE / "k2_residual_after_backreaction_summary.csv"
OUT_DOC = DOCS / "k2_residual_after_backreaction.md"


def chi2(residual: np.ndarray) -> float:
    return float(residual @ residual)


def corr(a: np.ndarray, b: np.ndarray) -> float:
    if len(a) < 2 or np.std(a) == 0.0 or np.std(b) == 0.0:
        return float("nan")
    return float(np.corrcoef(a, b)[0, 1])


def monotone_abs_gain(x: np.ndarray, y: np.ndarray) -> float:
    """Spearman-like slope proxy from x to abs(y), using linear slope."""
    if len(x) < 2:
        return float("nan")
    return float(np.polyfit(x, np.abs(y), 1)[0])


def summarize(route_id: str, subset_id: str, df: pd.DataFrame) -> dict[str, object]:
    target = df["WhitenedTarget"].to_numpy(float)
    k1 = df["K1Whitened"].to_numpy(float)
    k2 = df["K2LockedWhitened"].to_numpy(float)
    br_component = df["BackreactionLikeK2Component"].to_numpy(float)
    residual = df["K2ResidualFiniteMemoryComponent"].to_numpy(float)
    x = df["x_coordinate"].to_numpy(float) if "x_coordinate" in df.columns else df["z_grid"].to_numpy(float)
    stable = df["SignStable"].astype(bool).to_numpy()

    k2_chi = chi2(target - k2)
    residual_chi = chi2(target - residual)
    br_chi = chi2(target - br_component)
    k1_plus_residual_chi = chi2(target - (k1 + residual))
    k1_plus_k2_chi = chi2(target - (k1 + k2))
    residual_energy = float(residual @ residual)
    k2_energy = float(k2 @ k2)

    stable_target = target[stable]
    stable_residual = residual[stable]
    stable_sign_matches = int(np.sum(np.sign(stable_residual) == np.sign(stable_target))) if len(stable_target) else 0

    return {
        "DiagnosisID": "K2_RESIDUAL_AFTER_BACKREACTION_V1",
        "RouteID": route_id,
        "SubsetID": subset_id,
        "Rows": len(df),
        "StableRows": int(np.sum(stable)),
        "K2ResidualEnergy": residual_energy,
        "K2Energy": k2_energy,
        "ResidualEnergyFractionOfK2": residual_energy / k2_energy if k2_energy > 0 else float("nan"),
        "CorrelationResidualWithTarget": corr(residual, target),
        "CorrelationResidualWithBackreactionComponent": corr(residual, br_component),
        "ResidualAbsDepthSlope": monotone_abs_gain(x, residual),
        "K2AbsDepthSlope": monotone_abs_gain(x, k2),
        "ResidualChi2ToTarget": residual_chi,
        "BackreactionComponentChi2ToTarget": br_chi,
        "LockedK2Chi2ToTarget": k2_chi,
        "K1PlusResidualChi2ToTarget": k1_plus_residual_chi,
        "K1PlusLockedK2Chi2ToTarget": k1_plus_k2_chi,
        "ResidualBeatsBackreactionComponent": residual_chi < br_chi,
        "LockedK2BeatsResidualOnly": k2_chi < residual_chi,
        "StableResidualSignMatchesTarget": stable_sign_matches,
        "LockedK2Changed": False,
        "ScaleFitAllowed": False,
        "MeasurementValidationAllowed": False,
        "CurrentStatus": "FINITE_MEMORY_RESIDUAL_REMAINS_DIAGNOSTIC_COMPONENT",
        "ClaimBoundary": "k2_residual_after_backreaction_no_measurement_validation",
    }


def main() -> None:
    rows = pd.read_csv(SPLIT_ROW)
    # Keep one row per original route/subset diagnostic; avoid duplicate all-depth
    # rows contaminating subset summaries by using the explicit SubsetID already
    # generated by the component split.
    out = rows.copy()
    out["ResidualAbs"] = out["K2ResidualFiniteMemoryComponent"].abs()
    out["BackreactionComponentAbs"] = out["BackreactionLikeK2Component"].abs()
    out["ResidualDominatesBackreactionComponentHere"] = out["ResidualAbs"] > out["BackreactionComponentAbs"]
    out["ResidualSignMatchesTarget"] = (
        np.sign(out["K2ResidualFiniteMemoryComponent"]) == np.sign(out["WhitenedTarget"])
    )
    out["ResidualSignMatchesK2"] = (
        np.sign(out["K2ResidualFiniteMemoryComponent"]) == np.sign(out["K2LockedWhitened"])
    )
    out["ClaimBoundary"] = "k2_residual_after_backreaction_no_measurement_validation"
    out.to_csv(OUT_ROW, index=False)

    zone_rows = []
    for (route_id, subset_id), group in out.groupby(["RouteID", "SubsetID"], sort=True):
        zone_rows.append(summarize(route_id, subset_id, group))
    zone = pd.DataFrame(zone_rows)
    zone.to_csv(OUT_ZONE, index=False)

    mid_high = zone[zone["SubsetID"].eq("mid_high_depth")]
    high = zone[zone["SubsetID"].eq("high_depth")]
    summary = pd.DataFrame(
        [
            {
                "DiagnosisID": "K2_RESIDUAL_AFTER_BACKREACTION_V1",
                "Routes": zone["RouteID"].nunique(),
                "Subsets": len(zone),
                "MidHighResidualEnergyFractionMean": float(mid_high["ResidualEnergyFractionOfK2"].mean()),
                "HighResidualEnergyFractionMean": float(high["ResidualEnergyFractionOfK2"].mean()),
                "MidHighResidualTargetCorrelationMean": float(mid_high["CorrelationResidualWithTarget"].mean()),
                "HighResidualTargetCorrelationMean": float(high["CorrelationResidualWithTarget"].mean()),
                "MidHighResidualBeatsBackreactionComponentRoutes": int(mid_high["ResidualBeatsBackreactionComponent"].sum()),
                "HighResidualBeatsBackreactionComponentRoutes": int(high["ResidualBeatsBackreactionComponent"].sum()),
                "LockedK2Changed": False,
                "ScaleFitAllowed": False,
                "MeasurementValidationAllowed": False,
                "CurrentStatus": "FINITE_MEMORY_RESIDUAL_SURVIVES_BACKREACTION_COMPONENT_SPLIT",
                "StrongestAllowedClaim": (
                    "after removing a provisional backreaction-like component, a nonzero residual K2 component remains; "
                    "it is diagnostic support for a finite-memory residual, not measurement validation"
                ),
                "PrimaryResidualRisk": "residual depends on provisional backreaction bridge and whitening route",
                "NextAction": "repeat residual audit with source-native backreaction reconstruction and independent observable bridge",
                "ClaimBoundary": "k2_residual_after_backreaction_no_measurement_validation",
            }
        ]
    )
    summary.to_csv(OUT_SUMMARY, index=False)

    OUT_DOC.parent.mkdir(parents=True, exist_ok=True)
    OUT_DOC.write_text(
        "\n".join(
            [
                "# K2 Residual After Backreaction",
                "",
                "Status: diagnostic residual audit; locked K2 unchanged.",
                "",
                "This audit asks whether a K2 component remains after projecting out the provisional backreaction-like component. It does not create a new fitted model and does not authorize measurement validation.",
                "",
                "## Outputs",
                "",
                f"- Row audit: `{OUT_ROW.relative_to(ROOT)}`",
                f"- Zone audit: `{OUT_ZONE.relative_to(ROOT)}`",
                f"- Summary: `{OUT_SUMMARY.relative_to(ROOT)}`",
                "",
            ]
        ),
        encoding="utf-8",
    )

    print(f"Wrote {OUT_ROW}")
    print(f"Wrote {OUT_ZONE}")
    print(f"Wrote {OUT_SUMMARY}")
    print(f"Wrote {OUT_DOC}")


if __name__ == "__main__":
    main()
